# Generated by Django 4.2.1 on 2023-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="kategoriProduk",
            fields=[
                (
                    "nama",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nama Kategori:",
                    ),
                ),
                (
                    "deskripsi",
                    models.CharField(max_length=100, verbose_name="Deskripsi Kategori"),
                ),
            ],
        ),
    ]
