# Generated by Django 4.2.1 on 2023-05-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrasi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
        ),
    ]
