# Generated by Django 4.2.1 on 2023-05-22 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("administrasi", "0002_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kategoriproduk",
            old_name="nama",
            new_name="kategori",
        ),
        migrations.CreateModel(
            name="Produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "produk_kode",
                    models.CharField(max_length=100, verbose_name="Kode Produk"),
                ),
                (
                    "produk_nama",
                    models.CharField(max_length=200, verbose_name="Nama Produk"),
                ),
                (
                    "produk_serial",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Serial Kode Produk",
                    ),
                ),
                (
                    "produk_produsen",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Produken Produk",
                    ),
                ),
                ("stok_awal", models.IntegerField(default=0)),
                ("stok_masuk", models.IntegerField(default=0)),
                ("stok_keluar", models.IntegerField(default=0)),
                ("stok_akhir", models.IntegerField(default=0)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrasi.kategoriproduk",
                    ),
                ),
            ],
        ),
    ]
