# Generated by Django 4.2.1 on 2023-05-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0003_rename_nama_kategoriproduk_kategori_produk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='produk',
            name='stok_rusak',
            field=models.IntegerField(default=0, verbose_name='Stok Rusak'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok_akhir',
            field=models.IntegerField(default=0, verbose_name='Stok Akhir'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok_awal',
            field=models.IntegerField(default=0, verbose_name='Stok Awal'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok_keluar',
            field=models.IntegerField(default=0, verbose_name='Stok Keluar'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='stok_masuk',
            field=models.IntegerField(default=0, verbose_name='Stok Masuk'),
        ),
    ]
