# Generated by Django 4.2.1 on 2023-05-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrasi", "0004_delete_test_produk_stok_rusak_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategoriproduk",
            name="gambar",
            field=models.ImageField(
                null=True, upload_to="kategori", verbose_name="Gambar Kategori"
            ),
        ),
        migrations.AddField(
            model_name="produk",
            name="gambar",
            field=models.ImageField(
                null=True, upload_to="produk", verbose_name="Gambar Produk"
            ),
        ),
    ]
