# Generated by Django 4.2.1 on 2023-05-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrasi", "0007_remove_produk_id_alter_produk_produk_kode"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategoriproduk",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="produk",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
