# Generated by Django 4.2.1 on 2023-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0010_produk_berat_produk_deskripsi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='produk_serial',
            new_name='produk_merek',
        ),
        migrations.RemoveField(
            model_name='produk',
            name='produk_produsen',
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar1',
            field=models.ImageField(null=True, upload_to='produk', verbose_name='Gambar Produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar2',
            field=models.ImageField(null=True, upload_to='produk', verbose_name='Gambar Produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='gambar3',
            field=models.ImageField(null=True, upload_to='produk', verbose_name='Gambar Produk'),
        ),
        migrations.AddField(
            model_name='produk',
            name='grosir1',
            field=models.IntegerField(default=0, verbose_name='Grosir Tingkat #1'),
        ),
        migrations.AddField(
            model_name='produk',
            name='grosir2',
            field=models.IntegerField(default=0, verbose_name='Grosir Tingkat #2'),
        ),
        migrations.AddField(
            model_name='produk',
            name='grosir3',
            field=models.IntegerField(default=0, verbose_name='Grosir Tingkat #3'),
        ),
        migrations.AddField(
            model_name='produk',
            name='harga',
            field=models.IntegerField(default=0, verbose_name='Harga Eceran'),
        ),
        migrations.AddField(
            model_name='produk',
            name='jumlah1',
            field=models.IntegerField(default=0, verbose_name='Pembelian Tingkat #1'),
        ),
        migrations.AddField(
            model_name='produk',
            name='jumlah2',
            field=models.IntegerField(default=0, verbose_name='Pembelian Tingkat #2'),
        ),
        migrations.AddField(
            model_name='produk',
            name='jumlah3',
            field=models.IntegerField(default=0, verbose_name='Pembelian Tingkat #3'),
        ),
        migrations.AddField(
            model_name='produk',
            name='produk_asal',
            field=models.CharField(blank=True, choices=[('Indonesia', 'Indonesia'), ('Tiongkok', 'Tiongkok'), ('Amerika', 'Amerika'), ('Eropa', 'Eropa')], max_length=200, null=True, verbose_name='Produsen Produk'),
        ),
    ]
