# Generated by Django 4.2.1 on 2023-05-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrasi", "0011_rename_produk_serial_produk_produk_merek_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="upFilesKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myfile", models.FileField(null=True, upload_to="csv")),
            ],
        ),
        migrations.AlterField(
            model_name="produk",
            name="gambar",
            field=models.ImageField(
                blank=True, null=True, upload_to="produk", verbose_name="Gambar Produk"
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="gambar1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produk",
                verbose_name="Gambar Produk#1",
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="gambar2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produk",
                verbose_name="Gambar Produk#2",
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="gambar3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produk",
                verbose_name="Gambar Produk#3",
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="grosir1",
            field=models.IntegerField(
                default=0, verbose_name="Harga Grosir Tingkat #1"
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="grosir2",
            field=models.IntegerField(
                default=0, verbose_name="Harga Grosir Tingkat #2"
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="grosir3",
            field=models.IntegerField(
                default=0, verbose_name="Harga Grosir Tingkat #3"
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="jumlah1",
            field=models.IntegerField(
                default=0, verbose_name="Jumlah Pembelian Tingkat #1"
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="jumlah2",
            field=models.IntegerField(
                default=0, verbose_name="Jumlah Pembelian Tingkat #2"
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="jumlah3",
            field=models.IntegerField(
                default=0, verbose_name="Jumlah Pembelian Tingkat #3"
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="produk_asal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Indonesia", "Indonesia"),
                    ("Tiongkok", "Tiongkok"),
                    ("Amerika", "Amerika"),
                    ("Eropa", "Eropa"),
                ],
                max_length=200,
                null=True,
                verbose_name="Asal Negara",
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="produk_merek",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Kode SKU Produk"
            ),
        ),
    ]
