# Generated by Django 4.2.1 on 2023-05-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0014_kategoriproduk_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.kategoriproduk'),
        ),
    ]
