# Generated by Django 4.2.1 on 2023-05-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0015_produk_aktif_alter_produk_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='ada_transaksi',
            field=models.BooleanField(default=False),
        ),
    ]
