# Generated by Django 4.2.1 on 2023-05-30 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0016_produk_ada_transaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='rusakProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('jumlah_rusak', models.IntegerField(default=0, verbose_name='Jumlah Stok Rusak')),
                ('jumlah_ready', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Stok Diperbaiki/Retur')),
                ('keterangan', models.TextField(blank=True, max_length=200, null=True, verbose_name='Keterangan')),
                ('selesai', models.BooleanField(default=False)),
                ('produk_kode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.produk', verbose_name='Kode Produk')),
            ],
        ),
    ]
