# Generated by Django 4.2.1 on 2023-05-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0017_rusakproduk'),
    ]

    operations = [
        migrations.AddField(
            model_name='rusakproduk',
            name='jumlah_akhir',
            field=models.IntegerField(default=0, verbose_name='Result Jumlah Stok'),
        ),
        migrations.AlterField(
            model_name='rusakproduk',
            name='jumlah_ready',
            field=models.IntegerField(default=0, verbose_name='Jumlah Stok Diperbaiki/Retur'),
        ),
    ]
