# Generated by Django 4.2.1 on 2023-05-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0018_rusakproduk_jumlah_akhir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stok_revisi',
            field=models.IntegerField(default=0, verbose_name='Stok Revisi (Penambahan/ Pengurangan Manual)'),
        ),
        migrations.AlterField(
            model_name='rusakproduk',
            name='jumlah_akhir',
            field=models.IntegerField(default=0, verbose_name='Result Jumlah Stok Akhir Rusak'),
        ),
    ]
