# Generated by Django 4.2.1 on 2023-05-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0019_produk_stok_revisi_alter_rusakproduk_jumlah_akhir'),
    ]

    operations = [
        migrations.CreateModel(
            name='revisiProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('jumlah_revisi', models.IntegerField(default=0, verbose_name='Jumlah Stok Rusak')),
                ('keterangan', models.TextField(blank=True, max_length=200, null=True, verbose_name='Keterangan')),
                ('selesai', models.BooleanField(default=False)),
                ('produk_kode', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.produk', verbose_name='Kode Produk')),
            ],
        ),
    ]
