# Generated by Django 4.2.1 on 2023-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0020_revisiproduk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriproduk',
            name='deskripsi',
            field=models.TextField(max_length=100, verbose_name='Deskripsi Kategori'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Klik apabila status Produk Aktif'),
        ),
        migrations.AlterField(
            model_name='revisiproduk',
            name='selesai',
            field=models.BooleanField(default=False, verbose_name='Klik apabila status selesai'),
        ),
        migrations.AlterField(
            model_name='rusakproduk',
            name='selesai',
            field=models.BooleanField(default=False, verbose_name='Klik apabila status selesai'),
        ),
    ]
