# Generated by Django 4.2.1 on 2023-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0021_alter_kategoriproduk_deskripsi_alter_produk_aktif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Pilih Gambar untuk Banner')),
            ],
        ),
        migrations.AlterField(
            model_name='revisiproduk',
            name='jumlah_revisi',
            field=models.IntegerField(default=0, verbose_name='Jumlah Revisi Penambahan/ Pengurangan'),
        ),
    ]
