# Generated by Django 4.2.1 on 2023-06-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0024_produk_disc_produk_disc_mulai_produk_disc_selesai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='disc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumlah Discount (dalam %)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='disc_mulai',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai Discount'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='disc_selesai',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai Discount'),
        ),
    ]
