# Generated by Django 4.2.2 on 2023-06-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0025_alter_produk_disc_alter_produk_disc_mulai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='kategori',
            field=models.CharField(max_length=100, verbose_name='Kategori Produk'),
        ),
    ]
