# Generated by Django 4.2.3 on 2023-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0028_remove_produk_disc_selesai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='harga_nett',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Harga Setelah Discount'),
        ),
    ]
