# Generated by Django 4.2.3 on 2023-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0029_produk_harga_nett'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='dimensi_produk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ukuran Dimensi Packaging Produk (mis. 20cmx40cmx40cm)'),
        ),
        migrations.AddField(
            model_name='produk',
            name='kelengkapan_produk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Isikan Detail Kelengkapan Produk'),
        ),
    ]
