# Generated by Django 4.2.3 on 2023-07-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0032_produk_set_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterProvinsi',
            fields=[
                ('kode_provinsi', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Kode Provinsi (angka)')),
                ('nama_provinsi', models.CharField(max_length=200, verbose_name='Nama Provinsi')),
            ],
        ),
    ]
