# Generated by Django 4.2.1 on 2023-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0033_masterprovinsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadMasterProvinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='master_provinsi', verbose_name='Pilih File CSV')),
            ],
        ),
        migrations.AlterModelOptions(
            name='masterprovinsi',
            options={'ordering': ['kode_provinsi']},
        ),
    ]
