# Generated by Django 4.2.1 on 2023-07-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0034_uploadmasterprovinsi_alter_masterprovinsi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadMasterKota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='master_kota', verbose_name='Pilih File CSV')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='uploadmasterprovinsi',
            options={'ordering': ['id']},
        ),
    ]
