# Generated by Django 4.2.1 on 2023-07-31 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0036_masterkota'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadMasterDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='master_desa', verbose_name='Pilih File CSV')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='masterkota',
            options={'ordering': ['kode_provinsi', 'kode_kota']},
        ),
        migrations.AlterField(
            model_name='masterkota',
            name='kode_provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterprovinsi', verbose_name='Nama Provinsi'),
        ),
        migrations.CreateModel(
            name='masterDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_desa', models.IntegerField(default=0, verbose_name='Kode Desa (angka):')),
                ('nama_desa', models.CharField(max_length=200, verbose_name='Nama Kota')),
                ('kode_kota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterkota', verbose_name='Nama Kota')),
                ('kode_provinsi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrasi.masterprovinsi', verbose_name='Nama Provinsi')),
            ],
            options={
                'ordering': ['kode_provinsi', 'kode_kota'],
            },
        ),
    ]
