# Generated by Django 4.2.1 on 2023-07-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0037_uploadmasterdesa_alter_masterkota_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterdesa',
            options={'ordering': ['kode_provinsi', 'kode_kota', 'kode_desa']},
        ),
        migrations.AlterField(
            model_name='masterdesa',
            name='nama_desa',
            field=models.CharField(max_length=200, verbose_name='Nama Desa'),
        ),
    ]
